language: node_js
sudo: false
node_js:
        - "6.0"
install:
        - npm install
script:
        - echo "[.travis.yml] Iniciando ejecucion de test.sh"
        - sudo chmod +x test.sh
        - ./test.sh
        - echo "[.travis.yml] Finalizando ejecucion de test.sh"

deploy:
          provider: heroku
          api_key:
                        secure: "b45145e6-8c78-46ed-bb0d-46b8768ff133"
