language: node_js
sudo: false
node_js:
        - "6.0"
install:
        - npm install
script:
        - echo "[.travis.yml] Iniciando ejecucion de test.sh"
        - sudo chmod +x test.sh
        - ./test.sh
        - echo "[.travis.yml] Finalizando ejecucion de test.sh"

