language: node_js
sudo: false
node_js:
        - "6.0"
install:
        - npm install
script:
        - echo "iniciando test"
        - sudo chmod +x test.sh
        - ./test.sh
        - echo "finalizando test"

